apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: payment
  labels:
    app: payment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: server
          image: ifinodin/payment:v0.0.1
