apiVersion: v1

kind: Pod

metadata:
  name: web
  labels:
    app: web

spec:
  containers:
    - name: web
      image: ifinodin/otus-hw2:0.3
      volumeMounts:
        - name: web
          mountPath: /app
  initContainers:
    - name: init-web
      image: busybox:1.31.0
      command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
      volumeMounts:
        - name: web
          mountPath: /app
  volumes:
    - name: web
      emptyDir: {}
